### PR TITLE
Addressed issues for sprint 9/1/15

### PR DESCRIPTION
**Pull request by jmccausland**

### CODE REVIEW

**Comment by jmccausland** [comment]
Anyone have time for a pull request?  @csmoore @garys-esri

**Comment by garys-esri** [comment]
I can take it. @csmoore is already reviewing a pull request for me.

**Comment by garys-esri** [comment]
@jmccausland, I still get a crash when adding and deleting a phase. Here is what I'm doing specifically:

1. Run the application.
2. Click the **Add a new phase** button.
3. Click the **Edit** button. The **Edit Mission Phase** dialog appears with Phase 2 of 2 selected.
4. Click **Delete**, then click **Yes** on the confirm dialog.
5. Click **OK** to close the **Edit Mission Phase** dialog.
6. Click the **Edit** button again, and the application crashes.

I'm using Visual Studio 2012 and compiling on the command line (by the way, thanks for adding instructions for compiling on the command line). It's running as a 32-bit application.

**Comment by jmccausland** [comment]
@garys-esri The last fix should take care of the issue

**Comment by garys-esri** [comment]
Yes. that fixed it.

**Pull request merged**
